# This file is only used for local development and testing.
# - Overrides `docker-compose.yml` settings when running `docker compose up --build`
# - Mounts code for live development (useful for FastAPI changes).
# - Dynamically loads environment variables from `.env` for easier configuration.


services:
  api:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Use Redis password from .env file
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}  # Allow CORS from local frontend
      # - OLLAMA_DOCKER_TAG=${OLLAMA_DOCKER_TAG}  # Reference Ollama version from .env
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - OLLAMA_BASE_URL=http://ollama:11434  # Ensure API connects to local Ollama service
    volumes:
      - .:/code  # Mount local code for live updates
    ports:
      - "127.0.0.1:8000:8000"  # Restrict access to localhost only
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro  # Mount Redis config file (read-only)
      - redis_data:/data  # Ensure persistent storage

volumes:
  redis_data:



