services:
  api:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Injected via AWS Secrets Manager
    ports:
      - "8000:8000"

  redis:
    image: "redis:alpine"
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # Mount the Redis config file
      - redis_data:/data  # Persistent storage


volumes:
  redis_data: