services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    environment:
      API_URL: ${API_URL:-http://localhost:8000}
      INTERNAL_API_URL: ${INTERNAL_API_URL:-http://localhost:8000}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}          
      LLM_REFINE_ENDPOINT: ${LLM_REFINE_ENDPOINT:-http://llm-mock:8001/refine}
      LLM_ENHANCE_ENDPOINT: ${LLM_ENHANCE_ENDPOINT:-http://llm-mock:8001/enhance}
    depends_on:
      - llm_mock

  llm_mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-mock
    command: poetry run uvicorn app.mocks.llm_mock:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"