openapi: 3.0.3
info:
  title: Book Search API
  version: "1.0.0"
  description: >
    The Book Search API provides a RESTful interface for searching books using natural language queries.
    The service leverages an LLM to refine user queries and enhance retrieved book data from OpenLibrary.
    It is optimized for low latency (1-3 seconds response time).
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.production.com
    description: Production server
  - url: https://staging-api.production.com
    description: Staging server

paths:
  /search-books:
    post:
      summary: Search Books
      description: >
        Processes a natural language query to search for books. The query is refined using an LLM 
        before retrieving data from OpenLibrary. The response contains recommended books.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchBooksRequest"
      responses:
        "200":
          description: A successful response containing book recommendations.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchBooksResponse"
        "403":
          description: Request forbidden due to moderated content.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error (e.g., LLM or OpenLibrary failure).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    SearchBooksRequest:
      type: object
      properties:
        query:
          type: string
          description: The natural language search query.
      required:
        - query

    SearchBooksResponse:
      type: object
      properties:
        recommendations:
          type: array
          description: An array of recommended books.
          items:
            $ref: "#/components/schemas/Book"

    Book:
      type: object
      properties:
        title:
          type: string
        authors:
          type: array
          items:
            type: string
        description:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string