[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend service"
authors = ["Daniel Dayto <danielcdayto@gmail.com>"]
readme = "README.md"
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0" 
fastapi = ">=0.115,<0.120"
httpx = ">=0.28,<0.30"
uvicorn = ">=0.34,<0.40"
pydantic = ">=2.10,<3"
numpy = ">=2.2,<3"
pandas = ">=2.2,<3"
torch = ">=2.5,<3"
scikit-learn = ">=1.6,<2"
transformers = ">=4.48,<5"
python-dotenv = "^1.0.1"
pytest-env = "^1.1.5"
mangum = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3,<9"
pytest-asyncio = ">=0.25,<1"
black = ">=24,<25"
mypy = ">=1.10,<2"
ruff = ">=0.1,<1"
watchdog = "4.0.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
