name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      INTERNAL_API_URL: ${{ secrets.INTERNAL_API_URL }}
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      LLM_REFINE_ENDPOINT: ${{ secrets.LLM_REFINE_ENDPOINT }}
      LLM_ENHANCE_ENDPOINT: ${{ secrets.LLM_ENHANCE_ENDPOINT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: |
          cd backend
          docker compose up --build -d

      - name: Wait for API to be Ready
        run: |
          echo "Waiting for API..."
          for i in {1..30}; do
            curl --silent --fail http://localhost:8000/openapi.json && break
            sleep 2
          done
          echo "API is ready!"

      - name: Run Tests with pytest
        run: |
          cd backend
          docker exec backend-app poetry run pytest --maxfail=3 --disable-warnings -v

      - name: Tear Down Containers
        run: |
          cd backend
          docker compose down