name: Backend Tests

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 5s --health-retries 5

      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          cd backend
          docker compose up --build -d api

      - name: Wait for API to be Ready
        run: |
          echo "Waiting for API to be available..."
          timeout 60 bash -c 'until nc -z localhost 8000; do sleep 2; done' || (echo "API failed to start" && exit 1)
          echo "API is ready!"

      - name: Tear Down Containers
        if: always()
        run: |
          cd backend
          docker compose down
